### ISSUE TITLE
Unknown Parameter: field_name

### ISSUE THREAD

**Issue by junedc** [algolia/laravel-scout-algolia-macros#23]
- Algolia Client Version: 1.27
- Language Version:  

### Description
Trying to implement multiple params like the code below, but giving unknown parameter: title

 $posts = Product::search('')
                ->with(['title' => $request->get('q')])
                ->get();

### Steps To Reproduce

In my package.json
    "require": {
        "php": ">=7.1.3",
        "algolia/algoliasearch-client-php": "^1.27",
        "algolia/laravel-scout-algolia-macros": "^0.6.0",
        "laravel/framework": "5.6.*",
        "laravel/scout": "^5.0"
    },

Created a git code to reproduce the issue here https://github.com/junedc/scout-algolia-macros

**Comment by julienbourdeau** [comment]
Hi @junedc,

I'm not sure what you are trying to do here. `with` is meant to pass Algolia search parameters: https://www.algolia.com/doc/api-reference/search-api-parameters/

If you're trying to search only in the title with Algolia, it's possible but you need to use the `restrictSearchableAttributes` like:
```
$posts = Product::search($request->get('q'))
->with(['restrictSearchableAttributes' => ['title'])
->get();
```

You can find the doc here: https://www.algolia.com/doc/api-reference/api-parameters/restrictSearchableAttributes/

Please let me know if you're trying to do something else that I didn't get.

**Comment by junedc** [comment]
Hi @julienbourdeau  and thank you for your response.

I'm trying to use  'advance parameter' as in your example.

```
$params = [
            'aroundLatLng' => $lat.','.$lon,
            'hitsPerPage' => 30,
            'page' => 0,
            'aroundRadius' => 30000, //30km
            'aroundPrecision' => 200, //200 Meters
            'getRankingInfo' => true, //return ranking information in results
            'filters' => $filterString // add filters
        ];

$result = Model::search('')->with($params)->get(); 
```

And here's my controller implementation in Laravel

https://github.com/junedc/scout-algolia-macros/blob/master/app/Http/Controllers/Api/SearchController.php
in line 30 to 32

**Comment by julienbourdeau** [comment]
You can pass any Search parameters to `with`, but 'title' is not a valid Algolia parameter. Please refer to my previous answer for more details.
