### ISSUE TITLE
Compatiblity with laravel/scout ^6.0

### ISSUE THREAD

**Issue by riva-appi9** [algolia/laravel-scout-algolia-macros#24]
- Algolia Client Version: 1.28.0
- Language Version: PHP 7.1.23

### Description

Incompatiblity with latest version of `laravel/scout` which is 6.x.

### Steps To Reproduce
```bash
$ composer require algolia/laravel-scout-algolia-macros
Using version ^0.6.0 for algolia/laravel-scout-algolia-macros
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for algolia/laravel-scout-algolia-macros ^0.6.0 -> satisfiable by algolia/laravel-scout-algolia-macros[0.6.0].
    - algolia/laravel-scout-algolia-macros 0.6.0 requires laravel/scout 3.0.5 || ~4.0 || ~5.0 -> satisfiable by laravel/scout[4.0.x-dev, 5.0.x-dev, v3.0.5, v4.0.0, v4.0.1, v4.0.2, v4.0.3, v4.0.4, v5.0.0, v5.0.1, v5.0.2, v5.0.3] but these conflict with your requirements or minimum-stability.
```

**Comment by nunomaduro** [comment]
Thanks for reporting this issue.

At the end of the month, we are going to release the package **[Scout Extended](https://github.com/algolia/scout-extended)** - which brings the features of this package and **way more**!

Scout Extended is compatible with Laravel Scout 6.0 and it is currently in beta. You can already use it!

Concerning this package - we are going to archive it at the end of the month.
