### ISSUE TITLE
Use the new mixin feature

### ISSUE THREAD

**Issue by julienbourdeau** [algolia/laravel-scout-algolia-macros#7]
Laravel 5.5 will introduce a `mixin()` method to melt a class into another. The problem is that it would make this extension only compatible with Laravel 5.5.

```php
Builder::mixin(AlgoliaBuilderMacros::class);
```

See: https://github.com/laravel/framework/commit/353adbd696e36764227e39980272d38147899d14

**Comment by rayrutjes** [comment]
We could probably:
- keep functions to do the job
- keep a "macros" file for Laravel < 5.5 that simply use the functions
- create a new mixin class to be used with Laravel >= 5.5 that also use the functions

WDYT?

**Comment by nunomaduro** [comment]
I am going to close this since we are going to archive this package until the end of the month.
