### ISSUE TITLE
new withOpts macro

### ISSUE THREAD

**Issue by robbydooo** [algolia/laravel-scout-algolia-macros#8]
To give us the full power of Algolia could we add something like this

```php
if (! Builder::hasMacro('withOpts')) {
    /**
     * Override the algolia search options to give you full control over the request,
     * similar to official algolia-laravel package.
     *
     * Adds the final missing piece to scout to make the library useful.
     *
     * @param array $opts Latitude of the center
     *
     * @return Laravel\Scout\Builder
     */
    Builder::macro('withOpts', function ($opts) {
        $callback = $this->callback;

        $this->callback = function ($algolia, $query, $options) use ($opts, $callback) {
            $options = array_merge($options, $opts);

            if ($callback) {
                return call_user_func(
                    $callback,
                    $algolia,
                    $query,
                    $options
                );
            }

            return $algolia->search($query, $options);
        };

        return $this;
    });
}
```

So then we can do things like

```php

Accommodation::search('')->withOpts([
            'aroundLatLng' => $latitude.','.$longitude,
            'filters' => 'average_rating > 3'
             'aroundRadius' => 30000,
             'aroundPrecision' => 2000,
             'getRankingInfo' =>  true,
        ])->get()

```

This also gives us the ability to modify any of the options the same as the main algolia-laravel packages.
Not having full control over the options has been the one stumbling block for me not being able to use scout and I prefer how scout works with native models vs returning arrays in the Algolia package.

Thoughts?

**Comment by julienbourdeau** [comment]
Hi @robbydooo,

I think it's a great idea.

I started implementing more macros and I refactored the options in a private method. I think your approach is much better, it will make pretty much everything easy to achieve.

Do you want to make a Pull Request for this, so you get credits?

About the naming, what do you think of just `with`? It feels more Laravel-y.

**Comment by robbydooo** [comment]
Pull request has been requested and the macro name has been changed to "with" instead of "withOpts" as requested.

**Comment by robbydooo** [comment]
There is just one thing I am having trouble with regarding Scout and this approach, do we know how to retrieve the ranking info and any manually generated object elements once the models get rehydrated?

This approach works well with the exception of not yet working out how to get those pieces of information from the results.

Thanks for putting this library together in the first place!

**Comment by robbydooo** [comment]
As an update on this I have  found the reason why i am unable to gett access to the majority of the Algolia response.

I was unaware that Scout only uses the IDs for the models returned and they hydrates them from the database and so you lose all the additional data indexed and prevents you from accessing _rankingInfo and _highlightResult.

To me this is crazy and I have come up with a solution that gives you full control but it requires a change to Scout itself.

I have raised this issue and documented the benefits of changing this directly on Scouts repo here.

https://github.com/laravel/scout/issues/213

I am referencing it here as I am sure other people must need access to this information too. Please add your support if you would like full access to algolia searches meta data in your scout responses.

**Comment by julienbourdeau** [comment]
Hi @robbydooo 

Thanks a lot for bringing this up. We are working on some extra documentation about how to extend scout and do specific things. There will be an example about how to add highlighting. It should be published very soon.

If you need the highlighting, I assume it's because you're doing something in the view. Have you considered frontend search?

**Comment by robbydooo** [comment]
Hi @julienbourdeau ,

Many thanks for your response. I personally do not need _highlightResult but i do need _rankingInfo and also need access to some other data that we send through via the toSearchableArray() override.

As i have just mentioned in the other ticket on Laravel/Scout#213 you were correct in that this can be done with Macros which is awesome!

```php


if (! Builder::hasMacro('hydrate')) {
    /**
     * get() hydrates records by looking up the Ids in the corresponding database
     * This macro uses the data returned from the search results to hydrate
     *  the models and return a collection
     *
     * @return Collection
     */
    Builder::macro('hydrate', function () {
        $results = $this->engine()->search($this);

        if (count($results['hits']) === 0) {
            return Collection::make();
        }

        $hits = collect($results['hits']);
        $className = get_class($this->model);
        $models = new Collection();

        $hits->each(function($item, $key) use ($className, $models) {
            $models->push(new $className($item));
        });

        return $models;
    });
}
```

This then allows you to override the fill method on a model to populate the model with additional algolia data and more.

```php
class Location extends Model
{
    use Searchable;

    protected $rankingInfo = [];
    protected $highlightResult = [];

    /**
     * Adds the ranking & highlight results from the search request to get search score/geo distance etc
     *
     * @param array $attributes
     * @return mixed
     */
    public function fill(array $attributes)
    {

        if (isset($attributes['_rankingInfo']))
        {
            $this->setRankingInfo($attributes['_rankingInfo']);
        }

        if (isset($attributes['_highlightResult']))
        {
            $this->setHighlightResult($attributes['_highlightResult']);
        }

        return parent::fill($attributes);
    }

    public function getRankingInfoAttribute(): array
    {
        return $this->rankingInfo;
    }

    public function setRankingInfo(array $rankingInfo)
    {
        $this->rankingInfo = $rankingInfo;
    }

    /**
     * @return array
     */
    public function getHighlightResultAttribute(): array
    {
        return $this->highlightResult;
    }

    /**
     * @param array $highlightResult
     */
    public function setHighlightResult(array $highlightResult)
    {
        $this->highlightResult = $highlightResult;
    }


```

Is this something you would want in the main macros library? I can do a pull request if you think this is useful for other people.

Thanks,
Rob

**Comment by aaronhuisinga** [comment]
@robbydooo I for one think that would be a really useful PR. The alternative is basically just writing a custom Algolia driver for Scout as an extension that adds this stuff. Just adding these macros to the package would prevent me from having to do that.

Also, one small suggestion: Eloquent mass assignment is taken into account here, and it seems to me that it might be smart to override that for hydrating the models.

```php
Eloquent::unguard();

$hits->each(function ($item, $key) use ($className, $models) {
    $models->push(new $className($item));
});

Eloquent::reguard();
```

**Comment by robbydooo** [comment]
This is now pull request #10 

@aaronhuisinga thanks for suggestion, unguard has been added and credited to you.
